---
- name: reload shell
  debug:
    msg: "Shell configuration updated. Please run 'exec zsh -l' to apply changes."

- name: update brew
  become_user: "{{ dev_username }}"
  shell: "{{ brew_prefix }}/bin/brew update | cat"
  args:
    executable: /bin/bash
  listen: "brew update"
