---
- name: Install Biome.js globally
  become_user: "{{ dev_username }}"
  shell: |
    set -euo pipefail
    eval "$({{ brew_prefix }}/bin/fnm env)"
    npm install -g @biomejs/biome
  args:
    executable: /bin/bash
  tags:
    - install
    - biome
